name: Build Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install yarn
      run: npm install -g yarn

    - name: Install npmjs packages
      run: |
        cd frontend
        pnpm install

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Build project
      run: |
        cd frontend
        pnpm build